export const metadata = {
  title: "Non Profits",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <main className="bg-midnight-slate">
      <div className="container min-h-[calc(100dvh-56px)] flex items-center justify-center">
        <p className="animate-bounce">Cooking...</p>
      </div>
    </main>
  );
};

export default Page;
