import { BlurredImage } from "@/components/shared";
import {
  Button,
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from "@/components/ui";
import Link from "next/link";

export const metadata = {
  title: "Forgot Password",
  description: "Generated by create next app",
};

const ForgotPassword = () => {
  return (
    <main className="min-h-screen bg-black/5 flex items-center justify-center">
      <section className="grid grid-cols-1 lg:grid-cols-2 rounded-xl shadow-2xl border max-w-5xl cursor-pointer max-h-[80%]">
        {/* Left side*/}
        <div className="max-lg:hidden relative group">
          <BlurredImage
            src="https://images.pexels.com/photos/4384783/pexels-photo-4384783.jpeg"
            alt="Tech Image"
            className="rounded-l-xl"
          />

          {/* Dark overlay */}
          <div className="absolute inset-0 bg-black/25" />

          <div className="absolute bottom-0 w-full bg-black/50 p-5 space-y-1">
            <h6 className="text-white/90">Trouble Logging In?</h6>
            <p>We'll help you get back into your account.</p>
          </div>
        </div>

        {/* Right Side */}
        <div className="p-10 flex flex-col justify-center items-center gap-3.5 text-center">
          <div className="space-y-1">
            <h5>Forgot your Password</h5>
            <p>
              Enter your email address below and we'll send <br />
              you a otp to reset your password.
            </p>
          </div>

          <InputOTP maxLength={6}>
            <InputOTPGroup>
              <InputOTPSlot index={0} className="size-[50px]" />
              <InputOTPSlot index={1} className="size-[50px]" />
              <InputOTPSlot index={2} className="size-[50px]" />
            </InputOTPGroup>
            <InputOTPSeparator />
            <InputOTPGroup>
              <InputOTPSlot index={3} className="size-[50px]" />
              <InputOTPSlot index={4} className="size-[50px]" />
              <InputOTPSlot index={5} className="size-[50px]" />
            </InputOTPGroup>
          </InputOTP>

          <Button className="w-full bg-purple-600 hover:bg-purple-500">
            Send OTP
          </Button>

          <p>
            Remembered your password? {""}
            <Link
              href="/signup"
              className="text-purple-600 hover:text-purple-500 underline underline-offset-4 transition-colors duration-300 font-medium"
            >
              Back to Sign In
            </Link>
          </p>
        </div>
      </section>
    </main>
  );
};

export default ForgotPassword;
