import { SigninForm } from "@/components/forms";
import { BlurredImage } from "@/components/shared";

export const metadata = {
  title: "Signin",
  description: "Generated by create next app",
};

const Signin = () => {
  return (
    <main className="min-h-screen bg-black/5 flex items-center justify-center">
      <section className="flex items-center justify-between rounded-xl shadow-2xl border max-w-5xl">
        {/* Left side*/}
        <div className="h-full lg:w-[47%] max-lg:hidden relative">
          <BlurredImage
            src="https://images.pexels.com/photos/4384783/pexels-photo-4384783.jpeg"
            alt="Tech Image"
            className="rounded-l-xl w-full h-full"
          />

          {/* Dark overlay */}
          <div className="absolute inset-0 bg-black/25" />

          <div className="absolute bottom-0 w-full bg-black/50 p-5 space-y-1">
            <h6 className="text-white/90">Start Your Journey</h6>
            <p>Join thousands of users transforming their experience.</p>
          </div>
        </div>

        {/* Right Side */}
        <div className="w-full h-full lg:w-[53%] p-7">
          <div className="text-center space-y-1 pb-5">
            <h5>Welcome Back!</h5>
            <p>Manage your profile, and drive impact.</p>
          </div>

          <SigninForm />
        </div>
      </section>
    </main>
  );
};

export default Signin;
