import { SigninFrom } from "@/components/forms";
import { Card, CardContent, CardFooter, CardHeader } from "@/components/ui";
import Link from "next/link";

export const metadata = {
  title: "Signup",
  description: "Generated by create next app",
};

const Signin = () => {
  return (
    <main>
      <div className="min-h-dvh bg-slate-50 flex items-center justify-center">
        <Card className="w-full max-w-lg">
          <CardHeader className="text-center">
            <h6 className="text-xl">Welcome Back!</h6>
            <p>Manage your profile, and drive impact.</p>
          </CardHeader>

          <CardContent className="space-y-3.5">
            <SigninFrom />
          </CardContent>

          <CardFooter>
            <p>
              Don&apos;t have an account yet?{" "}
              <Link
                href="/signup"
                className="text-blue-600 hover:text-blue-500 underline underline-offset-4 transition-colors duration-300 font-medium"
              >
                Sign Up
              </Link>
            </p>
          </CardFooter>
        </Card>
      </div>
    </main>
  );
};

export default Signin;
