import data from "@/assets/data/blogs.json";
import { BlogCard } from "@/components/cards";

export const metadata = {
  title: "Blogs",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <main className="bg-midnight-slate py-10">
      <div className="container grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
        {data?.map((item) => (
          <BlogCard key={item?._id} data={item} />
        ))}
      </div>
    </main>
  );
};

export default Page;
