import Hero from "@/components/Hero";
import AboutUs from "@/components/AboutUs";
import Causes from "@/components/Causes";
import ImageGallery from "@/components/ImageGallery";
import HowWeWork from "@/components/HowWeWork";
import SupportEducation from "@/components/SupportEducation";
import Blogs from "@/components/Blogs";
import Events from "@/components/Events";
import Sponsors from "@/components/Sponsors";
import Testimonials from "@/components/Testimonials";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <main>
      <Hero />
      <Causes />
      <Events />
      <HowWeWork />
      <SupportEducation />
      <Testimonials />
      <AboutUs />
      <ImageGallery />
      <Blogs />
      <Sponsors />
    </main>
  );
};

export default Home;
