import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Us | Givify",
  description: "Generated by create next app",
};

const AboutUs = () => {
  return (
    <main className="bg-light-pearl dark:bg-midnight-slate py-10">
      <div className="min-h-[calc(100dvh-112px)] section-wrapper flex items-center justify-center">
        <p className="animate-bounce">Cooking...</p>
      </div>
    </main>
  );
};

export default AboutUs;
