export const metadata = {
  title: "Pricing",
  description: "Generated by create next app",
};

const Pricing = () => {
  return (
    <main className="bg-midnight-slate py-10">
      <div className="min-h-[calc(100dvh-112px)] section-wrapper flex items-center justify-center">
        <p className="animate-bounce">Cooking...</p>
      </div>
    </main>
  );
};

export default Pricing;
