export const metadata = {
  title: "Pricing",
  description: "Generated by create next app",
};

const Pricing = () => {
  return (
    <main className="bg-midnight-slate">
      <div className="section-wrapper min-h-[calc(100dvh-56px)] flex items-center justify-center">
        <p className="animate-bounce">Cooking...</p>
      </div>
    </main>
  );
};

export default Pricing;
