import data from "@/assets/data/donors.json";
import DonorLeaderboard from "@/components/DonorLeaderboard";

export const metadata = {
  title: "Leaderboard",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <main className="bg-midnight-slate py-[60px]">
      <div className="container">
        <DonorLeaderboard data={data} />
      </div>
    </main>
  );
};

export default Page;
