import data from "@/assets/data/pricing.json";
import PricingPlans from "@/components/PricingPlans";

export const metadata = {
  title: "Pricing",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <main className="bg-midnight-slate py-10">
      <div className="section-wrapper space-y-5">
        <div className="text-center space-y-2.5">
          <h4>Choose Your Plan</h4>
          <p>
            Flexible subscriptions designed to empower both individual donors
            and large organizations.
          </p>
        </div>

        <PricingPlans data={data} />
      </div>
    </main>
  );
};

export default Page;
