import type { Metadata } from "next";
import { Caveat, Poppins } from "next/font/google";
import { ReactNode } from "react";
import { cn } from "@/lib/utils";
import SmoothScrolling from "@/providers/smooth-scrolling";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: {
    default: "Givify",
    template: "%s | Givify",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={cn(poppins.className, "antialiased dark")}>
        <SmoothScrolling>{children}</SmoothScrolling>
      </body>
    </html>
  );
}
