import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ReactNode } from "react";
import { cn } from "@/lib/utils";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: {
    default: "Donatix",
    template: "%s | Donatix",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins?.className, "antialiased dark")}>
        <Analytics />
        {children}
      </body>
    </html>
  );
}
