import data from "@/assets/data/pricing.json";
import PricingPlans from "@/components/PricingPlans";

export const metadata = {
  title: "Pricing",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <main className="bg-midnight-slate max-lg:py-10">
      <div className="container min-h-[calc(100dvh-56px)] flex flex-col items-center justify-center space-y-5">
        <div className="text-center space-y-2.5">
          <h3>Choose Your Plan</h3>
          <p>
            Flexible subscriptions designed to empower both individual donors
            and large organizations.
          </p>
        </div>

        <PricingPlans data={data} />
      </div>
    </main>
  );
};

export default Page;
